name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Set git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

      - name: Add HF remote & pull/rebase
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://Youssef67887:${HF_TOKEN}@huggingface.co/spaces/Youssef67887/Search_engine
          git fetch hf main || true
          git rebase hf/main || true   # use 'git merge --no-edit hf/main' if you prefer merge
          git push hf HEAD:main
