name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: sync-to-hf
  cancel-in-progress: true

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    env:
      HF_SPACE: Youssef67887/Search_engine
      HF_USERNAME: Youssef67887
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS (optional)
        run: git lfs install --local

      - name: Configure git identity
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"

      - name: Add HF remote
        run: |
          git remote remove hf 2>/dev/null || true
          git remote add hf https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}

      - name: Force push to HF (overwrite remote)
        run: |
          git push hf HEAD:main --force-with-lease
